export enum VaultErrorCode {
	// Request
	REQUEST_BODY_REQUIRED = "VAULT.REQUEST.BODY_REQUIRED",
	REQUEST_JSON_PARSE_ERROR = "VAULT.REQUEST.JSON_PARSE_ERROR",
	REQUEST_QUERY_INVALID = "VAULT.REQUEST.QUERY_INVALID",
	REQUEST_PARAM_OUT_OF_RANGE = "VAULT.REQUEST.PARAM_OUT_OF_RANGE",
	REQUEST_VALIDATION_FAILED = "VAULT.REQUEST.VALIDATION_FAILED",
	REQUEST_BAD = "VAULT.REQUEST.BAD",
	REQUEST_DEPENDENCY_VALIDATION_FAILED = "VAULT.REQUEST.DEPENDENCY_VALIDATION_FAILED",
	REQUEST_UNSUPPORTED_VERSION = "VAULT.REQUEST.UNSUPPORTED_VERSION",
	REQUEST_METHOD_NOT_ALLOWED = "VAULT.REQUEST.METHOD_NOT_ALLOWED",
	REQUEST_PAYLOAD_TOO_LARGE = "VAULT.REQUEST.PAYLOAD_TOO_LARGE",
	REQUEST_UNSUPPORTED_MEDIA_TYPE = "VAULT.REQUEST.UNSUPPORTED_MEDIA_TYPE",
	REQUEST_RANGE_NOT_SATISFIABLE = "VAULT.REQUEST.RANGE_NOT_SATISFIABLE",

	// AuthZ/AuthN
	AUTH_MISSING_CREDENTIALS = "VAULT.AUTH.MISSING_CREDENTIALS",
	AUTH_INVALID_CREDENTIALS = "VAULT.AUTH.INVALID_CREDENTIALS",
	AUTH_INVALID_TOKEN = "VAULT.AUTH.INVALID_TOKEN",
	AUTH_EXPIRED_TOKEN = "VAULT.AUTH.EXPIRED_TOKEN",
	AUTH_REVOKED_TOKEN = "VAULT.AUTH.REVOKED_TOKEN",
	AUTH_MFA_REQUIRED = "VAULT.AUTH.MFA_REQUIRED",
	AUTH_INSUFFICIENT_SCOPE = "VAULT.AUTH.INSUFFICIENT_SCOPE",
	AUTH_FORBIDDEN = "VAULT.AUTH.FORBIDDEN",
	AUTH_CAPTCHA_REQUIRED = "VAULT.AUTH.CAPTCHA_REQUIRED",
	AUTH_EMAIL_NOT_VERIFIED = "VAULT.AUTH.EMAIL_NOT_VERIFIED",
	AUTH_PHONE_NOT_VERIFIED = "VAULT.AUTH.PHONE_NOT_VERIFIED",

	// Sessions
	SESSION_NOT_FOUND = "VAULT.SESSION.NOT_FOUND",
	SESSION_EXPIRED = "VAULT.SESSION.EXPIRED",
	SESSION_REVOKED = "VAULT.SESSION.REVOKED",
	SESSION_CONCURRENCY_LIMIT = "VAULT.SESSION.CONCURRENCY_LIMIT",
	SESSION_SECURITY_VIOLATION = "VAULT.SESSION.SECURITY_VIOLATION",

	// Users
	USER_NOT_FOUND = "VAULT.USER.NOT_FOUND",
	USER_DISABLED = "VAULT.USER.DISABLED",
	USER_ALREADY_EXISTS = "VAULT.USER.ALREADY_EXISTS",
	USER_EMAIL_TAKEN = "VAULT.USER.EMAIL_TAKEN",
	USER_USERNAME_TAKEN = "VAULT.USER.USERNAME_TAKEN",
	USER_INVALID_STATE = "VAULT.USER.INVALID_STATE",

	// Orgs
	ORG_NOT_FOUND = "VAULT.ORG.NOT_FOUND",
	ORG_SLUG_TAKEN = "VAULT.ORG.SLUG_TAKEN",
	ORG_MEMBER_NOT_FOUND = "VAULT.ORG.MEMBER_NOT_FOUND",
	ORG_ROLE_INVALID = "VAULT.ORG.ROLE_INVALID",
	ORG_ROLE_FORBIDDEN = "VAULT.ORG.ROLE_FORBIDDEN",
	ORG_MEMBER_LIMIT_EXCEEDED = "VAULT.ORG.MEMBER_LIMIT_EXCEEDED",

	// Resources
	RESOURCE_NOT_FOUND = "VAULT.RESOURCE.NOT_FOUND",
	RESOURCE_CONFLICT = "VAULT.RESOURCE.CONFLICT",
	RESOURCE_VERSION_CONFLICT = "VAULT.RESOURCE.VERSION_CONFLICT",
	RESOURCE_GONE = "VAULT.RESOURCE.GONE",
	RESOURCE_LOCKED = "VAULT.RESOURCE.LOCKED",

	// Idempotency
	IDEMPOTENCY_KEY_MISSING = "VAULT.IDEMPOTENCY.KEY_MISSING",
	IDEMPOTENCY_REPLAYED = "VAULT.IDEMPOTENCY.REPLAYED",
	IDEMPOTENCY_INCONSISTENT_REQUEST = "VAULT.IDEMPOTENCY.INCONSISTENT_REQUEST",

	// Rate limit
	RATE_LIMIT_EXCEEDED = "VAULT.RATE_LIMIT.EXCEEDED",
	RATE_LIMIT_GLOBAL_EXCEEDED = "VAULT.RATE_LIMIT.GLOBAL_EXCEEDED",
	RATE_LIMIT_SLOWDOWN = "VAULT.RATE_LIMIT.SLOWDOWN",
	RATE_LIMIT_BURST_EXCEEDED = "VAULT.RATE_LIMIT.BURST_EXCEEDED",

	// OTP / Email / Phone
	OTP_CODE_INVALID = "VAULT.OTP.CODE_INVALID",
	OTP_CODE_EXPIRED = "VAULT.OTP.CODE_EXPIRED",
	OTP_MAX_ATTEMPTS_EXCEEDED = "VAULT.OTP.MAX_ATTEMPTS_EXCEEDED",
	EMAIL_DELIVERY_FAILED = "VAULT.EMAIL.DELIVERY_FAILED",
	EMAIL_SEND_LIMIT_EXCEEDED = "VAULT.EMAIL.SEND_LIMIT_EXCEEDED",
	EMAIL_ALREADY_VERIFIED = "VAULT.EMAIL.ALREADY_VERIFIED",
	PHONE_DELIVERY_FAILED = "VAULT.PHONE.DELIVERY_FAILED",
	PHONE_SEND_LIMIT_EXCEEDED = "VAULT.PHONE.SEND_LIMIT_EXCEEDED",
	PHONE_ALREADY_VERIFIED = "VAULT.PHONE.ALREADY_VERIFIED",

	// MFA
	MFA_CHALLENGE_REQUIRED = "VAULT.MFA.CHALLENGE_REQUIRED",
	MFA_CODE_INVALID = "VAULT.MFA.CODE_INVALID",
	MFA_CODE_EXPIRED = "VAULT.MFA.CODE_EXPIRED",
	MFA_ENROLLMENT_REQUIRED = "VAULT.MFA.ENROLLMENT_REQUIRED",
	MFA_FACTOR_LOCKED = "VAULT.MFA.FACTOR_LOCKED",

	// Tokens / crypto
	TOKEN_SIGNATURE_INVALID = "VAULT.TOKEN.SIGNATURE_INVALID",
	TOKEN_ALGORITHM_UNSUPPORTED = "VAULT.TOKEN.ALGORITHM_UNSUPPORTED",
	TOKEN_KID_UNKNOWN = "VAULT.TOKEN.KID_UNKNOWN",
	TOKEN_NOT_BEFORE = "VAULT.TOKEN.NOT_BEFORE",

	// OAuth / OIDC / SAML
	OAUTH_INVALID_REDIRECT_URI = "VAULT.OAUTH.INVALID_REDIRECT_URI",
	OAUTH_STATE_MISMATCH = "VAULT.OAUTH.STATE_MISMATCH",
	OAUTH_CODE_EXCHANGE_FAILED = "VAULT.OAUTH.CODE_EXCHANGE_FAILED",
	OAUTH_PROVIDER_UNAVAILABLE = "VAULT.OAUTH.PROVIDER_UNAVAILABLE",
	OIDC_NONCE_MISMATCH = "VAULT.OIDC.NONCE_MISMATCH",
	SAML_RESPONSE_INVALID = "VAULT.SAML.RESPONSE_INVALID",
	SAML_CLOCK_SKEW = "VAULT.SAML.CLOCK_SKEW",

	// Webhooks
	WEBHOOK_SIGNATURE_INVALID = "VAULT.WEBHOOK.SIGNATURE_INVALID",
	WEBHOOK_TIMESTAMP_OUT_OF_TOLERANCE = "VAULT.WEBHOOK.TIMESTAMP_OUT_OF_TOLERANCE",
	WEBHOOK_EVENT_UNSUPPORTED = "VAULT.WEBHOOK.EVENT_UNSUPPORTED",
	WEBHOOK_ENDPOINT_GONE = "VAULT.WEBHOOK.ENDPOINT_GONE",

	// Storage
	STORAGE_FILE_TOO_LARGE = "VAULT.STORAGE.FILE_TOO_LARGE",
	STORAGE_MEDIA_TYPE_UNSUPPORTED = "VAULT.STORAGE.MEDIA_TYPE_UNSUPPORTED",
	STORAGE_VIRUS_DETECTED = "VAULT.STORAGE.VIRUS_DETECTED",
	STORAGE_UPLOAD_INCOMPLETE = "VAULT.STORAGE.UPLOAD_INCOMPLETE",

	// Billing
	BILLING_PAYMENT_REQUIRED = "VAULT.BILLING.PAYMENT_REQUIRED",
	BILLING_SUBSCRIPTION_PAST_DUE = "VAULT.BILLING.SUBSCRIPTION_PAST_DUE",
	BILLING_PLAN_LIMIT_EXCEEDED = "VAULT.BILLING.PLAN_LIMIT_EXCEEDED",

	// Security
	SECURITY_SIGNATURE_INVALID = "VAULT.SECURITY.SIGNATURE_INVALID",
	SECURITY_REPLAY_DETECTED = "VAULT.SECURITY.REPLAY_DETECTED",
	SECURITY_SUSPECTED_ABUSE = "VAULT.SECURITY.SUSPECTED_ABUSE",
	SECURITY_IP_BLOCKED = "VAULT.SECURITY.IP_BLOCKED",

	// Infra / server
	UPSTREAM_TIMEOUT = "VAULT.UPSTREAM.TIMEOUT",
	UPSTREAM_BAD_GATEWAY = "VAULT.UPSTREAM.BAD_GATEWAY",
	UPSTREAM_UNAVAILABLE = "VAULT.UPSTREAM.UNAVAILABLE",
	DATABASE_UNIQUE_CONSTRAINT = "VAULT.DATABASE.UNIQUE_CONSTRAINT",
	DATABASE_TIMEOUT = "VAULT.DATABASE.TIMEOUT",
	CACHE_UNAVAILABLE = "VAULT.CACHE.UNAVAILABLE",
	QUEUE_UNAVAILABLE = "VAULT.QUEUE.UNAVAILABLE",
	SERVER_ERROR = "VAULT.SERVER.ERROR",
	SERVER_MAINTENANCE = "VAULT.SERVER.MAINTENANCE",
	SERVER_TIMEOUT = "VAULT.SERVER.TIMEOUT",
}

// export const ErrorCodeMessages: Record<VaultErrorCode, string> = {
//     [ErrorCode.UNKNOWN_ERROR]: "An unknown error occurred",
//     [ErrorCode.VALIDATION_ERROR]: "Validation failed",
//     [ErrorCode.DATABASE_ERROR]: "Database operation failed",
//     [ErrorCode.INVALID_CREDENTIALS]: "Invalid email or password",
//     [ErrorCode.ACCESS_TOKEN_EXPIRED]: "Access token expired",
//     [ErrorCode.REFRESH_TOKEN_EXPIRED]: "Refresh token expired",
//     [ErrorCode.ACCOUNT_LOCKED]: "Account is temporarily locked",
//     [ErrorCode.RESOURCE_NOT_FOUND]: "Requested resource not found",
//     [ErrorCode.RESOURCE_CONFLICT]: "Resource already exists",
//     [ErrorCode.RESOURCE_LIMIT_REACHED]: "Resource limit reached",
//     [ErrorCode.UNAUTHORIZED_ACCESS]: "Unauthorized access",
//     [ErrorCode.INSUFFICIENT_PERMISSIONS]: "Insufficient permissions",
//     [ErrorCode.INVALID_OPERATION]: "Invalid operation",
//     [ErrorCode.PAYMENT_REQUIRED]: "Payment required",
//     [ErrorCode.EXTERNAL_SERVICE_FAILURE]: "External service failure",
//     [ErrorCode.THIRD_PARTY_API_ERROR]: "Third-party API error",
//     [ErrorCode.AUTH_EMAIL_ALREADY_EXISTS]: "User with this email already exists",
//     [ErrorCode.AUTH_USER_CREATION_FAILED]: "User creation failed, please try again later",
// };

// Request & input (400/405/413/415/422)

// VAULT.REQUEST.BODY_REQUIRED – 400 – Body missing

// VAULT.REQUEST.JSON_PARSE_ERROR – 400 – Invalid JSON

// VAULT.REQUEST.QUERY_INVALID – 400 – Bad querystring

// VAULT.REQUEST.PARAM_OUT_OF_RANGE – 422 – Value out of bounds

// VAULT.REQUEST.VALIDATION_FAILED – 422 – Schema/semantic errors

// VAULT.REQUEST.DEPENDENCY_VALIDATION_FAILED – 422 – Cross-field constraint failed

// VAULT.REQUEST.UNSUPPORTED_VERSION – 400 – API version not supported

// VAULT.REQUEST.METHOD_NOT_ALLOWED – 405 – Wrong HTTP verb

// VAULT.REQUEST.PAYLOAD_TOO_LARGE – 413 – Exceeds size limit

// VAULT.REQUEST.UNSUPPORTED_MEDIA_TYPE – 415 – Wrong Content-Type

// VAULT.REQUEST.RANGE_NOT_SATISFIABLE – 416 – Bad Range header

// Authentication (401) & Authorization (403)

// VAULT.AUTH.MISSING_CREDENTIALS – 401 – No auth presented

// VAULT.AUTH.INVALID_CREDENTIALS – 401 – Bad email/password

// VAULT.AUTH.INVALID_TOKEN – 401 – Token can’t be verified

// VAULT.AUTH.EXPIRED_TOKEN – 401 – Token expired

// VAULT.AUTH.REVOKED_TOKEN – 401 – Token revoked

// VAULT.AUTH.MFA_REQUIRED – 401 – Second factor needed

// VAULT.AUTH.INSUFFICIENT_SCOPE – 403 – Lacking scopes/claims

// VAULT.AUTH.FORBIDDEN – 403 – Authenticated but not allowed

// VAULT.AUTH.CAPTCHA_REQUIRED – 403 – Human verification needed

// VAULT.AUTH.EMAIL_NOT_VERIFIED – 403 – Email verification gate

// VAULT.AUTH.PHONE_NOT_VERIFIED – 403 – Phone verification gate

// Sessions

// VAULT.SESSION.NOT_FOUND – 401 – No active session

// VAULT.SESSION.EXPIRED – 401 – Session timed out

// VAULT.SESSION.REVOKED – 401 – Session revoked

// VAULT.SESSION.CONCURRENCY_LIMIT – 429 – Too many active sessions

// VAULT.SESSION.SECURITY_VIOLATION – 403 – UA/IP/geo mismatch policy

// Users & profiles

// VAULT.USER.NOT_FOUND – 404 – User missing

// VAULT.USER.DISABLED – 403 – User blocked

// VAULT.USER.ALREADY_EXISTS – 409 – Duplicate user

// VAULT.USER.EMAIL_TAKEN – 409 – Email already in use

// VAULT.USER.USERNAME_TAKEN – 409 – Handle already in use

// VAULT.USER.INVALID_STATE – 409 – State prevents operation

// Organizations / Tenants

// VAULT.ORG.NOT_FOUND – 404 – Org missing

// VAULT.ORG.SLUG_TAKEN – 409 – Duplicate org slug

// VAULT.ORG.MEMBER_NOT_FOUND – 404 – Member missing

// VAULT.ORG.ROLE_INVALID – 422 – Unknown/invalid role

// VAULT.ORG.ROLE_FORBIDDEN – 403 – Not allowed to assign role

// VAULT.ORG.MEMBER_LIMIT_EXCEEDED – 403 – Plan/limit gate

// Resources (generic CRUD)

// VAULT.RESOURCE.NOT_FOUND – 404 – Any missing entity

// VAULT.RESOURCE.CONFLICT – 409 – Uniqueness/state conflict

// VAULT.RESOURCE.VERSION_CONFLICT – 409 – ETag / If-Match failed

// VAULT.RESOURCE.GONE – 410 – Permanently removed

// VAULT.RESOURCE.LOCKED – 423 – Write blocked

// Idempotency & concurrency

// VAULT.IDEMPOTENCY.KEY_MISSING – 400 – No Idempotency-Key

// VAULT.IDEMPOTENCY.REPLAYED – 409 – Key already used (diff result)

// VAULT.IDEMPOTENCY.INCONSISTENT_REQUEST – 409 – Same key, different body

// Rate limiting (429)

// VAULT.RATE_LIMIT.EXCEEDED – 429 – Per-route limit reached

// VAULT.RATE_LIMIT.GLOBAL_EXCEEDED – 429 – Global/project limit

// VAULT.RATE_LIMIT.SLOWDOWN – 429 – Back-off requested

// VAULT.RATE_LIMIT.BURST_EXCEEDED – 429 – Burst bucket drained

// OTP / Email / SMS

// VAULT.OTP.CODE_INVALID – 401 – Wrong code

// VAULT.OTP.CODE_EXPIRED – 401 – Code expired

// VAULT.OTP.MAX_ATTEMPTS_EXCEEDED – 429 – Too many tries

// VAULT.EMAIL.DELIVERY_FAILED – 502 – Mail provider error

// VAULT.EMAIL.SEND_LIMIT_EXCEEDED – 429 – Too many emails

// VAULT.EMAIL.ALREADY_VERIFIED – 409 – Nothing to verify

// VAULT.PHONE.DELIVERY_FAILED – 502 – SMS provider error

// VAULT.PHONE.SEND_LIMIT_EXCEEDED – 429 – Too many SMS

// VAULT.PHONE.ALREADY_VERIFIED – 409 – Nothing to verify

// MFA factors

// VAULT.MFA.CHALLENGE_REQUIRED – 401 – Start/complete challenge

// VAULT.MFA.CODE_INVALID – 401 – TOTP/SMS code wrong

// VAULT.MFA.CODE_EXPIRED – 401 – Code too old

// VAULT.MFA.ENROLLMENT_REQUIRED – 403 – Factor not enrolled

// VAULT.MFA.FACTOR_LOCKED – 423 – Too many failures

// Tokens / crypto

// VAULT.TOKEN.SIGNATURE_INVALID – 401 – Signature mismatch

// VAULT.TOKEN.ALGORITHM_UNSUPPORTED – 401 – JWT alg not allowed

// VAULT.TOKEN.KID_UNKNOWN – 401 – Unknown signing key

// VAULT.TOKEN.NOT_BEFORE – 401 – Token not active yet

// OAuth / OIDC / SAML / SSO

// VAULT.OAUTH.INVALID_REDIRECT_URI – 400 – Redirect not allowed

// VAULT.OAUTH.STATE_MISMATCH – 400 – CSRF protection failed

// VAULT.OAUTH.CODE_EXCHANGE_FAILED – 400 – Token exchange error

// VAULT.OAUTH.PROVIDER_UNAVAILABLE – 502 – IdP outage

// VAULT.OIDC.NONCE_MISMATCH – 401 – OIDC replay protection

// VAULT.SAML.RESPONSE_INVALID – 400 – Bad SAML response

// VAULT.SAML.CLOCK_SKEW – 401 – Outside allowed skew

// Webhooks

// VAULT.WEBHOOK.SIGNATURE_INVALID – 401 – Bad webhook signature

// VAULT.WEBHOOK.TIMESTAMP_OUT_OF_TOLERANCE – 401 – Replay window

// VAULT.WEBHOOK.EVENT_UNSUPPORTED – 400 – Unknown event type

// VAULT.WEBHOOK.ENDPOINT_GONE – 410 – Receiver removed

// Storage / uploads

// VAULT.STORAGE.FILE_TOO_LARGE – 413 – Size over limit

// VAULT.STORAGE.MEDIA_TYPE_UNSUPPORTED – 415 – Bad file type

// VAULT.STORAGE.VIRUS_DETECTED – 422 – Malware detected

// VAULT.STORAGE.UPLOAD_INCOMPLETE – 400 – Multipart/integrity failed

// Billing / plans

// VAULT.BILLING.PAYMENT_REQUIRED – 402 – Payment needed

// VAULT.BILLING.SUBSCRIPTION_PAST_DUE – 402 – Subscription issue

// VAULT.BILLING.PLAN_LIMIT_EXCEEDED – 403 – Feature/seat cap

// Security & abuse

// VAULT.SECURITY.SIGNATURE_INVALID – 401 – HMAC/JWS failed

// VAULT.SECURITY.REPLAY_DETECTED – 409 – Reused nonce/timestamp

// VAULT.SECURITY.SUSPECTED_ABUSE – 403 – Risk engine block

// VAULT.SECURITY.IP_BLOCKED – 403 – Network policy

// Infrastructure / upstream / server

// VAULT.UPSTREAM.TIMEOUT – 502 – Provider timed out

// VAULT.UPSTREAM.BAD_GATEWAY – 502 – Invalid upstream response

// VAULT.UPSTREAM.UNAVAILABLE – 503 – Upstream down

// VAULT.DATABASE.UNIQUE_CONSTRAINT – 409 – DB uniqueness hit

// VAULT.DATABASE.TIMEOUT – 503 – DB timeout

// VAULT.CACHE.UNAVAILABLE – 503 – Cache miss/outage

// VAULT.QUEUE.UNAVAILABLE – 503 – Queue/backpressure

// VAULT.SERVER.ERROR – 500 – Generic internal error

// VAULT.SERVER.MAINTENANCE – 503 – Planned maintenance

// VAULT.SERVER.TIMEOUT – 504 – Request timed out
